# services:
#   app:
#     build: .
#     ports:
#       - "8080:8080"
#     depends_on:
#       - postgres_db
#     volumes:
#       - .:/app

#   postgres_db:
#     image: postgres:14-alpine
#     restart: always
#     environment:
#       POSTGRES_USER: admin
#       POSTGRES_PASSWORD: admin
#       POSTGRES_DB: hw_08_db
#     ports:
#       - "5432:5432"
services:
  app:
    build: .
    # ...
    depends_on:
      - postgres_db
    volumes:
      - .:/app
    env_file:
      - .env

  migration:
    build: .
    volumes:
      - .:/app
    depends_on:
      - postgres_db
    env_file:
      - .env.docker
    command: ["alembic", "revision", "--autogenerate", "-m", "Initial migration"] # <--- Команда для міграції

  postgres_db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_ui
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres_db

volumes:
  postgres_data:



# services:
#   app:
#     build: .
#     ports:
#       - "8080:8080"
#     depends_on:
#       - postgres_db
#     volumes:
#       - .:/app
#     env_file:
#       - .env

#   postgres_db:
#     image: postgres:14-alpine
#     restart: always
#     environment:
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASS}
#       POSTGRES_DB: ${DB_NAME}
#     ports:
#       - "5432:5432"

